// You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Return the letter that was added to t.

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Input: s = "", t = "y"
// Output: "y"

package findthedifference

func findTheDifference(s string, t string) byte {
	visited := map[rune]int{}
	for _, r := range s {
		visited[r]++
	}
	for _, r := range t {
		visited[r]--
	}
	for k, v := range visited {
		if v == -1 {
			return byte(k)
		}
	}
	return byte(t[0])
}

// func findTheDifference(s string, t string) byte {
// 	var diff byte
// 	for i := range s {
// 		diff ^= s[i]
// 	}
// 	for i := range t {
// 		diff ^= t[i]
// 	}
// 	return diff
// }
